# The Container ID looks like 'GTM-XXXXX'.
google_tag_manager:
privacy_policy_uri: /privacy-policy

# Manages where Tag Manager script will be loaded.
zones:
  # Load on front end pages. Defaults to true.
  frontend: true
  # Load on back end/admin pages. Defaults to false.
  backend: false
